jackdcrawford/five

README.md, five.js, test.js
=> Added latvian support.

README.md, five.js, test.js
=> Update five.js with Serbian support

README.md, five.js, test.js
In true Node fashion:
```javascript
five.async(function(err, five) {
// five === 5
});
```
=> Implements asynchronous access to 5

README.md, five.js, test.js
=> Added support for an Estonian five

README.md, five.js, test.js
Adds
```javascript
five.oclock(); // '🕔'
```
=> Add o'clock

README.md, five.js, test.js
=> Fix for Morse code of 5

README.md
We should be able to donate to this awesome project.
This money should go to awesome 5 stickers and other merch.
This PR adds a donate link to the readme.md
How much should people donate? Five of course!
=> Adding donate five

README.md
=> Update donations in readme

index.html
```diff
-five.belarusian <span class="pl-c">// пяць</span>
+five.belarusian() <span class="pl-c">// пяць</span>
```
=> Site typo fix

README.md, five.js, test.js
https://dictionary.cambridge.org/dictionary/english/fiver
=> Added fiver

README.md, five.js
This adds the ability to call five.funk() which returns a string to provide you a low down on 5ive, blowing your mind so you gotta get into Five. What you waiting for? If you wanna three (three), two (two), one, let's do it.
=> What you waiting for?

README.md, five.js, test.js
=> add five.nepali()

README.md, five.js, test.js
This PR adds the Law of Fives. Something which is perfectly suited to this project.
It comes from Discordianism:
http://discordia.wikia.com/wiki/Law_of_Fives
=> Add the Law of Fives

README.md, five.js, test.js
I created a method for high five...
o/
=> Added high five method

README.md, five.js, test.js
Citizens of the Valley of Peace! It is my great honor to present to you... Tigress! Viper! Crane! Monkey! Mantis! The Furious Five!
=> Added Furious Five

README.md, five.js, test.js
=> Add support for esperanto

README.md, five.js, test.js
=> Adding Punjabi support (ਪੰਜ)

README.md, five.js, test.js
It's always five o'Clock somewhere right? Time for a cold one.
=> Added "Its five oclock somewhere"

README.md, five.js, test.js
returns 5*4*3*2*1 optimized at 500% normal factorial runtime
=> Five Factorial

README.md, five.js, test.js
Adds support for Enid Blighton's central characters from The Famous Five via `five.famous()`
=> Add The Famous Five

README.md, five.js, test.js
=> Add five bucks

README.md, five.js, test.js
Add five.euro() and five.dollar //5€ a 5$
=> Add five.euro() and five.dollar //5€ a 5$

README.md, five.js, test.js
Fixed the glaring omission of Daft Punk's [Interstella 5555: The 5tory of the 5ecret 5tar 5ystem](https://en.wikipedia.org/wiki/Interstella_5555:_The_5tory_of_the_5ecret_5tar_5ystem)
=> Added "Interstella 5555: The 5tory of the 5ecret 5tar 5ystem"
